name: Sync Mediawiki Interface Codes

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - src/**/*.js
      - src/**/*.css
      - src/**/.options

# Disallow parallel running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync_codes:
    runs-on: ubuntu-latest
    env:
      MW_BOT_PASSWORD: ${{ secrets.MW_BOT_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Synchronize with Mediawiki
        run: |
          pip install -r scripts/requirements.txt
          python scripts/sync_mediawiki.py
